site_name: "SFG Analytics Platform"
site_description: "Documentation hub for Salt Free Gaming's business intelligence platform"
site_url: "https://saltfreegaming.github.io/analytics-docs"
repo_url: "https://github.com/saltfreegaming/analytics-docs"
site_dir: static
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - content.code.copy
nav:
  - Home: index.md
  - Credits: credits.md
  - Project Management:
      - Dashboard Workflows: project-management/dashboard-workflows.md
      - Overview: project-management/stakeholder-overview.md
      - Dashboard Requests: project-management/dashboard-requests/index.md
      - Data Entity Taxonomy:
          - Dota Taxonomy: project-management/data-entity-taxonomy/dota-taxonomy.md
      - Decision Briefs:
          - Inaccurate Account Calibration: project-management/decision-briefs/inaccurate-account-calibration.md
  - Analytics Frameworks:
      - Signal Catalog: analytics-frameworks/signal-catalog.md
  - Platform:
      - Apache Superset:
          - Software Details: platform/superset.md
          - Style Guidelines: platform/superset-style-guidelines.md
      - Design:
          - Known Limitations: platform/design/limitations.md
  - Dashboards:
      - Dashboard docs go here...: dashboards/final-dashboard-docs-here.md
  - Templates & Checklists:
      - Dashboard Request: templates-and-checklists/dashboard-request.md
      - Dashboard Documentation Template: templates-and-checklists/dashboard-template.md
extra:
  analytics_phase: "minimum"
